//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakipV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmet
    {
        public Hizmet()
        {
            this.YapilanIs = new HashSet<YapilanIs>();
        }
    
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Aciklama { get; set; }
        public int Durumu { get; set; }
        public int Musteri_Id { get; set; }
        public int Sinif_Id { get; set; }
        public Nullable<double> Ucret { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Sinif Sinif { get; set; }
        public virtual ICollection<YapilanIs> YapilanIs { get; set; }
    }
}
