//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakipV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka
    {
        public Marka()
        {
            this.Sinif = new HashSet<Sinif>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<Sinif> Sinif { get; set; }
    }
}
