//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakipV3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakipSistemiEntities : DbContext
    {
        public TakipSistemiEntities()
            : base("name=TakipSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hizmet> Hizmet { get; set; }
        public DbSet<HizmetResim> HizmetResim { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Marka> Marka { get; set; }
        public DbSet<Musteri> Musteri { get; set; }
        public DbSet<Sinif> Sinif { get; set; }
        public DbSet<YapilanIs> YapilanIs { get; set; }
    }
}
